apiVersion: apps/v1
kind: Deployment
metadata:
  name: mindful-moments-deployment
spec:
  selector:
    matchLabels:
      app: mindful-moments
  replicas: 2
  template:
    metadata:
      labels:
        app: mindful-moments
    spec:
      containers:
        - name: mindful-moments
          image: app_web:latest
          ports:
            - containerPort: 8000
          imagePullPolicy: Never # when deploying into minikube